model:
  model_name: meta-llama/Llama-3.2-1B-Instruct
  model_max_length: 8192
  torch_dtype_str: bfloat16
  attn_implementation: "sdpa"
  load_pretrained_weights: True
  trust_remote_code: True

training:
  trainer_type: TRL_SFT
  output_dir: output/llama1b.fft
  num_train_epochs: 3
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 4
  optimizer: "adamw_torch_fused"
  learning_rate: 2.0e-5
  logging_steps: 10
  save_steps: 100
  enable_gradient_checkpointing: False
  compile: False
  dataloader_num_workers: "auto"
  dataloader_prefetch_factor: 32
  empty_device_cache_steps: 50
  include_performance_metrics: True
  enable_wandb: False

data:
  train:
    datasets:
      - dataset_name: tatsu-lab/alpaca
        split: train
